    version: 2
    jobs:
      build:
        machine:
          image: ubuntu-2004:202010-01 
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .
          - run:    
              name: Test Docker image core imports (NumPy, FEniCS)
              command: |
                  docker run -p 8890:8892  -e USER_PASS=Scientific $IMAGE_NAME:latest /bin/bash -c "python -c \"import numpy; print(numpy.__path__); from dolfin import *;\""
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push $IMAGE_NAME:latest
              no_output_timeout: 17600

    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
